version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/primergpt
    restart: unless-stopped
    networks:
      - primergpt-network

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_AUTH_ENABLED=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=primergpt
      - WEBHOOK_URL=http://n8n:5678/
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
    volumes:
      - n8n-data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - primergpt-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - primergpt-network

networks:
  primergpt-network:
    driver: bridge

volumes:
  ollama-data:
  n8n-data:
